# Generated by Django 2.0.5 on 2018-05-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('NombreCientifico', models.CharField(blank=True, max_length=50)),
                ('Subtitulo', models.CharField(blank=True, max_length=200)),
                ('Positivos', models.CharField(blank=True, max_length=100)),
                ('Negativos', models.CharField(blank=True, max_length=100)),
                ('Descripcion', models.CharField(blank=True, max_length=5000)),
                ('DescripcionCorta', models.CharField(blank=True, max_length=1000)),
                ('Pregunta1', models.CharField(max_length=200)),
                ('Pregunta2', models.CharField(blank=True, max_length=200)),
                ('Pregunta3', models.CharField(blank=True, max_length=200)),
                ('Pregunta4', models.CharField(blank=True, max_length=200)),
                ('Pregunta5', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Esencia1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia1', to='Esencias.Esencia')),
                ('Esencia10', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia10', to='Esencias.Esencia')),
                ('Esencia2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia2', to='Esencias.Esencia')),
                ('Esencia3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia3', to='Esencias.Esencia')),
                ('Esencia4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia4', to='Esencias.Esencia')),
                ('Esencia5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia5', to='Esencias.Esencia')),
                ('Esencia6', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia6', to='Esencias.Esencia')),
                ('Esencia7', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia7', to='Esencias.Esencia')),
                ('Esencia8', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia8', to='Esencias.Esencia')),
                ('Esencia9', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_Esencia9', to='Esencias.Esencia')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sintoma', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subsintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subsintoma', models.CharField(max_length=200)),
                ('Esencia1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsintoma_Esencia1', to='Esencias.Esencia')),
                ('Esencia2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsintoma_Esencia2', to='Esencias.Esencia')),
                ('Esencia3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsintoma_Esencia3', to='Esencias.Esencia')),
                ('Sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Esencias.Sintoma')),
            ],
        ),
    ]
