# Generated by Django 2.0.5 on 2018-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='Esencia1',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia10',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia2',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia3',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia4',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia5',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia6',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia7',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia8',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='Esencia9',
        ),
        migrations.RemoveField(
            model_name='subsintoma',
            name='Esencia1',
        ),
        migrations.RemoveField(
            model_name='subsintoma',
            name='Esencia2',
        ),
        migrations.RemoveField(
            model_name='subsintoma',
            name='Esencia3',
        ),
        migrations.AddField(
            model_name='formula',
            name='Esencia',
            field=models.ManyToManyField(to='Esencias.Esencia'),
        ),
        migrations.AddField(
            model_name='subsintoma',
            name='Esencia',
            field=models.ManyToManyField(to='Esencias.Esencia'),
        ),
    ]
