# Generated by Django 2.0.5 on 2018-05-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0002_auto_20180525_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='esencia',
            name='Imagen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='esencia',
            name='TestIntuitivo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
