# Generated by Django 2.0.5 on 2018-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0004_auto_20180526_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsintoma',
            name='Esencia',
        ),
        migrations.AddField(
            model_name='subsintoma',
            name='Esencia',
            field=models.ManyToManyField(to='Esencias.Esencia'),
        ),
    ]
