# Generated by Django 2.0.5 on 2018-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0005_auto_20180526_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsintoma',
            name='Descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
