# Generated by Django 2.0.5 on 2018-05-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0007_nuevaesencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
