# Generated by Django 2.0.5 on 2018-05-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0008_formula_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevaesencia',
            name='Nueva',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
