# Generated by Django 2.0.5 on 2018-05-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0009_nuevaesencia_nueva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevaesencia',
            name='Nueva',
        ),
    ]
