# Generated by Django 2.0.5 on 2018-05-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0010_remove_nuevaesencia_nueva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuevaEsencia',
        ),
        migrations.AddField(
            model_name='esencia',
            name='Nueva',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
