# Generated by Django 2.0.5 on 2018-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0011_auto_20180526_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esencia',
            old_name='DescripcionCorta',
            new_name='Descripcion Corta',
        ),
        migrations.RenameField(
            model_name='esencia',
            old_name='NombreCientifico',
            new_name='Nombre Cientifico',
        ),
        migrations.RenameField(
            model_name='esencia',
            old_name='TestIntuitivo',
            new_name='Test Intuitivo',
        ),
        migrations.RemoveField(
            model_name='esencia',
            name='Nueva',
        ),
        migrations.AddField(
            model_name='esencia',
            name='Set',
            field=models.CharField(choices=[('V', 'Set 100 Flores'), ('N', 'Nuevas Flores')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Descripcion',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta1',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
