# Generated by Django 2.0.5 on 2018-05-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0012_auto_20180530_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esencia',
            name='Set',
            field=models.CharField(choices=[('0', 'Set 100 Flores'), ('1', 'Nuevas Flores')], default='V', max_length=1),
        ),
    ]
