# Generated by Django 2.0.5 on 2018-05-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0013_auto_20180530_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esencia',
            old_name='Descripcion Corta',
            new_name='DescripcionCorta',
        ),
        migrations.RenameField(
            model_name='esencia',
            old_name='Nombre Cientifico',
            new_name='NombreCientifico',
        ),
        migrations.RenameField(
            model_name='esencia',
            old_name='Test Intuitivo',
            new_name='TestIntuitivo',
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Set',
            field=models.CharField(choices=[('0', 'Set 100 Flores'), ('1', 'Nuevas Flores')], default='0', max_length=1),
        ),
    ]
