# Generated by Django 2.0.5 on 2018-06-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0014_auto_20180530_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esencia',
            old_name='Set',
            new_name='Sets',
        ),
    ]
