# Generated by Django 2.0.5 on 2018-06-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0015_auto_20180605_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esencia',
            name='Negativos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Positivos',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
