# Generated by Django 2.0.5 on 2018-06-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0017_auto_20180606_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esencia',
            name='Descripcion',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='DescripcionCorta',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Imagen',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Negativos',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='NombreCientifico',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Positivos',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='TestIntuitivo',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
