# Generated by Django 2.0.5 on 2018-06-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0018_auto_20180606_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esencia',
            name='Imagen',
            field=models.CharField(blank=True, max_length=304),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Negativos',
            field=models.CharField(blank=True, max_length=303),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Positivos',
            field=models.CharField(blank=True, max_length=302),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta1',
            field=models.CharField(blank=True, max_length=305),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta2',
            field=models.CharField(blank=True, max_length=306),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta3',
            field=models.CharField(blank=True, max_length=307),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta4',
            field=models.CharField(blank=True, max_length=308),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Pregunta5',
            field=models.CharField(blank=True, max_length=309),
        ),
        migrations.AlterField(
            model_name='esencia',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=301),
        ),
    ]
