# Generated by Django 2.0.5 on 2018-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0019_auto_20180606_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsintoma',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
