# Generated by Django 2.0.5 on 2018-06-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0020_auto_20180618_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsintoma',
            name='Formula',
            field=models.ManyToManyField(to='Esencias.Formula'),
        ),
    ]
