# Generated by Django 2.0.5 on 2018-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0021_subsintoma_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='SubFormula',
            field=models.ManyToManyField(related_name='_formula_SubFormula_+', to='Esencias.Formula'),
        ),
        migrations.AlterField(
            model_name='subsintoma',
            name='Esencia',
            field=models.ManyToManyField(blank=True, to='Esencias.Esencia'),
        ),
        migrations.AlterField(
            model_name='subsintoma',
            name='Formula',
            field=models.ManyToManyField(blank=True, to='Esencias.Formula'),
        ),
    ]
