# Generated by Django 2.0.5 on 2018-07-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0022_auto_20180618_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='Descripcion',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='formula',
            name='DescripcionCorta',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='formula',
            name='Imagen',
            field=models.CharField(blank=True, max_length=304),
        ),
        migrations.AddField(
            model_name='formula',
            name='Negativos',
            field=models.CharField(blank=True, max_length=303),
        ),
        migrations.AddField(
            model_name='formula',
            name='Positivos',
            field=models.CharField(blank=True, max_length=302),
        ),
        migrations.AddField(
            model_name='formula',
            name='Pregunta1',
            field=models.CharField(blank=True, max_length=305),
        ),
        migrations.AddField(
            model_name='formula',
            name='Pregunta2',
            field=models.CharField(blank=True, max_length=306),
        ),
        migrations.AddField(
            model_name='formula',
            name='Pregunta3',
            field=models.CharField(blank=True, max_length=307),
        ),
        migrations.AddField(
            model_name='formula',
            name='Pregunta4',
            field=models.CharField(blank=True, max_length=308),
        ),
        migrations.AddField(
            model_name='formula',
            name='Pregunta5',
            field=models.CharField(blank=True, max_length=309),
        ),
        migrations.AddField(
            model_name='formula',
            name='TestIntuitivo',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='formula',
            name='SubFormula',
            field=models.ManyToManyField(blank=True, to='Esencias.Formula'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=301),
        ),
    ]
