# Generated by Django 2.0.5 on 2018-07-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0024_remove_formula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='Personalizada',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
