# Generated by Django 2.0.5 on 2018-07-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0025_formula_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='Personalizada',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1),
        ),
    ]
