# Generated by Django 2.0.5 on 2018-08-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0028_remove_paciente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Recomendado',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
