# Generated by Django 2.0.5 on 2018-08-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0030_esencia_plusinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='FechaNacimiento',
            field=models.DateField(blank=True),
        ),
    ]
