# Generated by Django 2.0.5 on 2018-08-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0031_auto_20180804_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='FechaNacimiento',
            field=models.DateTimeField(blank=True),
        ),
    ]
