# Generated by Django 2.0.5 on 2018-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0033_auto_20180804_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Abortos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Abortos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Alimentacion',
            field=models.CharField(choices=[('M', 'Mala'), ('R', 'Regular'), ('B', 'Buena')], default='N', max_length=1, verbose_name='Alimentacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Anemia',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1, verbose_name='Anemia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='AntecFamilMental',
            field=models.CharField(blank=True, max_length=200, verbose_name='Antecedentes de Salud Mental en Familiares'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Apellido',
            field=models.CharField(max_length=35, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Constelaciones',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si'), ('U', 'Ultimo Año'), ('M', 'Mas de 1 Año')], default='N', max_length=1, verbose_name='Constelaciones'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='DetalleSistemas',
            field=models.CharField(blank=True, max_length=500, verbose_name='¿Que sistemas?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Diabetes',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Sin Insulina'), ('C', 'Con Insulina')], default='N', max_length=1, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Direccion',
            field=models.CharField(blank=True, max_length=60, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Direccion de E-Mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='EnfermedadesActuales',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enfermedades actuales'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='EnfermedadesPasadas',
            field=models.CharField(blank=True, max_length=200, verbose_name='Enfermedades en el Pasado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='FechaNacimiento',
            field=models.DateField(blank=True, max_length=60, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Hermanos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hermanos?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Hijos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hijos y Edades'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='HoraNacimiento',
            field=models.TimeField(blank=True, default='00:00:00', max_length=60, verbose_name='Hora de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Localidad',
            field=models.CharField(blank=True, max_length=30, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='LugarNacimiento',
            field=models.CharField(blank=True, max_length=60, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Medicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Toma Algun Medicacion?'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='MotivoVisita',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Motivo de la visita'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Nombre',
            field=models.CharField(max_length=35, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Operaciones',
            field=models.CharField(blank=True, max_length=200, verbose_name='Operaciones'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='OtrosSistemas',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1, verbose_name='Otros Sistemas'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Pareja',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1, verbose_name='Pareja'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ParejaTiempo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tiempo en Pareja'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Profesion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Psicologo',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si'), ('U', 'Ultimo Año'), ('M', 'Mas de 1 Año')], default='N', max_length=1, verbose_name='Psicologo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Recomendado',
            field=models.CharField(blank=True, max_length=70, verbose_name='Recomendado por'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Yoga',
            field=models.CharField(choices=[('N', 'No'), ('S', 'Si'), ('U', 'Ultimo Año'), ('M', 'Mas de 1 Año')], default='N', max_length=1, verbose_name='Yoga'),
        ),
    ]
