# Generated by Django 2.0.5 on 2018-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0034_auto_20180805_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Hermanos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hermanos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Hijos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hijos'),
        ),
    ]
