# Generated by Django 2.0.5 on 2018-08-05 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0035_auto_20180805_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='FechaAlta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
