# Generated by Django 2.0.5 on 2018-08-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0036_paciente_fechaalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='esencia',
            name='Efecto',
            field=models.CharField(choices=[('D', 'Desconocido'), ('S', 'Sedativa'), ('A', 'Activadora'), ('B', 'Ambas')], default='D', max_length=1),
        ),
    ]
