# Generated by Django 2.0.5 on 2018-08-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0041_auto_20180822_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esencia',
            name='Efecto',
        ),
    ]
