# Generated by Django 2.0.5 on 2018-08-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0043_esencia_efecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Medicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Toma Alguna Medicacion?'),
        ),
    ]
