# Generated by Django 2.0.5 on 2018-08-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0044_auto_20180822_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Sexo',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=1, verbose_name='Sexo'),
        ),
    ]
