# Generated by Django 2.0.5 on 2018-08-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esencias', '0045_auto_20180823_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Alimentacion',
            field=models.CharField(choices=[('Mala', 'Mala'), ('Regular', 'Regular'), ('Buena', 'Buena')], default='N', max_length=12, verbose_name='Alimentacion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Anemia',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='N', max_length=12, verbose_name='Anemia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Constelaciones',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si'), ('Ultimo Año', 'Ultimo Año'), ('Mas de 1 Año', 'Mas de 1 Año')], default='N', max_length=12, verbose_name='Constelaciones'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Diabetes',
            field=models.CharField(choices=[('No', 'No'), ('Sin Insulina', 'Sin Insulina'), ('Con Insulina', 'Con Insulina')], default='N', max_length=12, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='OtrosSistemas',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='N', max_length=12, verbose_name='Otros Sistemas'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Pareja',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='N', max_length=12, verbose_name='Pareja'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Psicologo',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si'), ('Ultimo Año', 'Ultimo Año'), ('Mas de 1 Año', 'Mas de 1 Año')], default='N', max_length=12, verbose_name='Psicologo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Sexo',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=12, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Yoga',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si'), ('Ultimo Año', 'Ultimo Año'), ('Mas de 1 Año', 'Mas de 1 Año')], default='N', max_length=12, verbose_name='Yoga'),
        ),
    ]
