# Generated by Django 2.0.5 on 2018-05-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(auto_now_add=True)),
                ('Observaciones', models.CharField(blank=True, max_length=2000)),
                ('Receta', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=35)),
                ('DNI', models.CharField(blank=True, max_length=12)),
                ('FechaNacimiento', models.DateField(blank=True)),
                ('Sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('Direccion', models.CharField(blank=True, max_length=60)),
                ('Telefono', models.CharField(blank=True, max_length=20)),
                ('Localidad', models.CharField(blank=True, max_length=30)),
                ('Email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.Paciente'),
        ),
    ]
