# Generated by Django 2.0.5 on 2018-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
