# Generated by Django 2.0.5 on 2018-07-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0002_auto_20180525_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Psicologo',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('S', 'Si')], default='N', max_length=1),
        ),
    ]
